---
- name: Configure FireWall | Open port Node Exporter
  firewalld:
    port: 9100/tcp
    permanent: true
    state: enabled
  register: change_rules

- name: Configure FireWall | Restart firewalld
  systemd:
    name: firewalld
    state: reloaded
  when: change_rules.changed
